# Generated by Django 5.2.1 on 2025-05-16 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('ID_azienda', models.AutoField(primary_key=True, serialize=False)),
                ('nome_azienda', models.CharField(max_length=100)),
                ('sede_legale', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Componenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('tipologia', models.CharField(max_length=50)),
                ('prezzo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('immagine', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_utente', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechHub.componenti')),
            ],
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('ID_ordine', models.AutoField(primary_key=True, serialize=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('attesa', 'In attesa'), ('spedito', 'Spedito'), ('consegnato', 'Consegnato'), ('annullato', 'Annullato')], max_length=20)),
                ('componenti', models.ManyToManyField(through='TechHub.Contiene', to='TechHub.componenti')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to='TechHub.utente')),
            ],
        ),
        migrations.AddField(
            model_name='contiene',
            name='ordine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechHub.ordine'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('ID_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('metodo', models.CharField(choices=[('carta', 'Carta'), ('paypal', 'PayPal')], max_length=20)),
                ('esito', models.CharField(choices=[('riuscito', 'Riuscito'), ('fallito', 'Fallito')], max_length=20)),
                ('ordine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='TechHub.ordine')),
            ],
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('ID_recensione', models.AutoField(primary_key=True, serialize=False)),
                ('voto', models.IntegerField()),
                ('testo', models.TextField()),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='TechHub.componenti')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='TechHub.utente')),
            ],
        ),
    ]
