# Generated by Django 5.2.1 on 2025-05-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenti',
            name='immagine',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
