# Generated by Django 5.2.1 on 2025-05-21 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechHub', '0002_alter_componenti_immagine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='componenti',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='ordine',
        ),
        migrations.AddField(
            model_name='componenti',
            name='azienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='componenti', to='TechHub.azienda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordine',
            name='marca',
            field=models.CharField(default='Marca sconosciuta', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordine',
            name='nome',
            field=models.CharField(default='Nome sconosciuto', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordine',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordine',
            name='tipologia',
            field=models.CharField(default='Tipologia sconosciuta', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='azienda',
            name='nome_azienda',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Contiene',
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
