# Generated by Django 5.2.1 on 2025-05-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechHub', '0004_ordine_componenti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recensione',
            name='componente',
        ),
        migrations.AddField(
            model_name='recensione',
            name='titolo',
            field=models.CharField(default='Titolo sconosciuto', max_length=100),
            preserve_default=False,
        ),
    ]
