# Generated by Django 5.2.1 on 2025-05-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechHub', '0005_remove_recensione_componente_recensione_titolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='titolo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
