# Generated by Django 5.2.1 on 2025-06-27 18:52

import TechHub.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('ID_azienda', models.AutoField(primary_key=True, serialize=False)),
                ('nome_azienda', models.CharField(max_length=100, unique=True)),
                ('sede_legale', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('ID_giveaway', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=100)),
                ('immagine', models.URLField()),
                ('data_inizio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fine', models.DateTimeField(default=TechHub.models.default_data_fine)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_utente', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ruolo', models.CharField(choices=[('privato', 'Utente Privato'), ('azienda', 'Azienda')], max_length=10)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nazionalita', models.CharField(blank=True, max_length=50, null=True)),
                ('partita_iva', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_aziendale', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Componenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('tipologia', models.CharField(max_length=50)),
                ('prezzo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('immagine', models.URLField(blank=True, max_length=500, null=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componenti', to='TechHub.azienda')),
            ],
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('ID_recensione', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(default='', max_length=100)),
                ('voto', models.IntegerField()),
                ('testo', models.TextField()),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='TechHub.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('ID_ordine', models.AutoField(primary_key=True, serialize=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('attesa', 'In attesa'), ('spedito', 'Spedito'), ('consegnato', 'Consegnato'), ('annullato', 'Annullato')], max_length=20)),
                ('sconto_applicato', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('tipologia', models.CharField(max_length=50)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('componenti', models.ManyToManyField(to='TechHub.componenti')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to='TechHub.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Partecipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechHub.giveaway')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechHub.utente')),
            ],
            options={
                'unique_together': {('utente', 'giveaway')},
            },
        ),
    ]
