# Generated by Django 5.2.1 on 2025-05-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechHub', '0003_remove_ordine_componenti_remove_pagamento_ordine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='componenti',
            field=models.ManyToManyField(to='TechHub.componenti'),
        ),
    ]
