# Generated by Django 5.2.1 on 2025-06-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechHub', '0006_alter_recensione_titolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='data_nascita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utente',
            name='nazionalita',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='utente',
            name='partita_iva',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='utente',
            name='ruolo',
            field=models.CharField(choices=[('privato', 'Utente Privato'), ('azienda', 'Azienda')], default='Utente privato', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='utente',
            name='telefono_aziendale',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
