# Generated by Django 5.2.1 on 2025-06-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechHub', '0007_utente_data_nascita_utente_nazionalita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='sconto_applicato',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
